//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinServDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIMFinServDBEntities : DbContext
    {
        public AIMFinServDBEntities()
            : base("name=AIMFinServDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblApplicantCommunicationDetail> tblApplicantCommunicationDetails { get; set; }
        public virtual DbSet<tblApplicantEmploymentDetail> tblApplicantEmploymentDetails { get; set; }
        public virtual DbSet<tblApplicantExpenseSheet> tblApplicantExpenseSheets { get; set; }
        public virtual DbSet<tblApplicant> tblApplicants { get; set; }
        public virtual DbSet<tblApplicantType> tblApplicantTypes { get; set; }
        public virtual DbSet<tblAsset> tblAssets { get; set; }
        public virtual DbSet<tblAssetType> tblAssetTypes { get; set; }
        public virtual DbSet<tblExpenseType> tblExpenseTypes { get; set; }
        public virtual DbSet<tblLiability> tblLiabilities { get; set; }
        public virtual DbSet<tblLiabilityType> tblLiabilityTypes { get; set; }
        public virtual DbSet<tblMasterTypeOfEmployment> tblMasterTypeOfEmployments { get; set; }
        public virtual DbSet<tblMasterTypeOfProfession> tblMasterTypeOfProfessions { get; set; }
        public virtual DbSet<tblMasterTypeOfQualification> tblMasterTypeOfQualifications { get; set; }
        public virtual DbSet<tblMasterTypeOfRelationship> tblMasterTypeOfRelationships { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUsersRole> tblUsersRoles { get; set; }
    }
}
