//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinServDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblApplicant()
        {
            this.tblApplicantCommunicationDetails = new HashSet<tblApplicantCommunicationDetail>();
            this.tblApplicantExpenseSheets = new HashSet<tblApplicantExpenseSheet>();
            this.tblApplicantQualificationDetails = new HashSet<tblApplicantQualificationDetail>();
            this.tblAssets = new HashSet<tblAsset>();
            this.tblLiabilities = new HashSet<tblLiability>();
        }
    
        public long AutoID { get; set; }
        public System.Guid ApplicantID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string NoOfDependents { get; set; }
        public Nullable<bool> NZResidents { get; set; }
        public string CountryOfBirth { get; set; }
        public int ApplicantTypeID { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string HomePhoneNo { get; set; }
        public string WorkPhoneNo { get; set; }
        public System.Guid LoanApplicationNo { get; set; }
        public Nullable<int> FileTypeID { get; set; }
        public string FileName { get; set; }
        public byte[] ApplicantImage { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicantCommunicationDetail> tblApplicantCommunicationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicantExpenseSheet> tblApplicantExpenseSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicantQualificationDetail> tblApplicantQualificationDetails { get; set; }
        public virtual tblLoanApplicationForm tblLoanApplicationForm { get; set; }
        public virtual tblMasterApplicantType tblMasterApplicantType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAsset> tblAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLiability> tblLiabilities { get; set; }
        public string FileType { get; set; }
        public object tblMasterFileType { get; set; }
    }
}
