//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinServDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantCommunicationDetail
    {
        public long AutoID { get; set; }
        public System.Guid CommunicationID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Duration { get; set; }
        public string Status { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public int AddressType { get; set; }
        public System.Guid ApplicantID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual tblMasterAddressType tblMasterAddressType { get; set; }
        public virtual tblApplicant tblApplicant { get; set; }
    }
}
