//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinServDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanMaster
    {
        public long AutoID { get; set; }
        public System.Guid LANNumber { get; set; }
        public Nullable<System.Guid> LoanApplicationNo { get; set; }
        public string ROIOffered { get; set; }
        public string LoanTermOffered { get; set; }
        public string RateTypeOffered { get; set; }
        public string FrequencyOffered { get; set; }
        public string LoanValueRatio { get; set; }
        public string LoanAmountOffered { get; set; }
        public string LoanType { get; set; }
        public string ClientID { get; set; }
        public string Status { get; set; }
        public string EMIStartDay { get; set; }
        public string EMIStartMonth { get; set; }
        public string LoanProcessingFee { get; set; }
        public string AnyLegalCharges { get; set; }
        public string NoOfEMI { get; set; }
        public string Loanprovider { get; set; }
        public string PropertyCost { get; set; }
        public string PropertyType { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
