//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinServDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanApplicationForm
    {
        public long AutoID { get; set; }
        public System.Guid LoanApplicationNo { get; set; }
        public System.Guid ApplicantID { get; set; }
        public Nullable<bool> IsPreApproval { get; set; }
        public string TypeOfLoan { get; set; }
        public string Priority { get; set; }
        public string FinanceRequired { get; set; }
        public string CashInHand { get; set; }
        public string LoanTerm { get; set; }
        public string RateType { get; set; }
        public string Frequency { get; set; }
        public Nullable<bool> IsApplicationApproved { get; set; }
        public Nullable<System.DateTime> ApprovalExpiryDate { get; set; }
        public string ReasonForNotApproval { get; set; }
        public Nullable<bool> IsAnyGuarantor { get; set; }
        public string CostOfProperty { get; set; }
        public string PropertyType { get; set; }
        public Nullable<bool> IsShifted { get; set; }
        public string AgeOfProperty { get; set; }
        public string ShiftedDuration { get; set; }
        public string PropertyUsedFor { get; set; }
        public Nullable<bool> IsPropertyDecided { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual tblApplicant tblApplicant { get; set; }
    }
}
