//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinServDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanApplicationForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoanApplicationForm()
        {
            this.tblApplicants = new HashSet<tblApplicant>();
            this.tblLoanGuarantors = new HashSet<tblLoanGuarantor>();
            this.tblLoanMasters = new HashSet<tblLoanMaster>();
        }
    
        public long AutoID { get; set; }
        public System.Guid LoanApplicationNo { get; set; }
        public string ApplicationFormNumber { get; set; }
        public Nullable<bool> IsPreApproval { get; set; }
        public int TypeOfLoanID { get; set; }
        public int PurposeOfLoanID { get; set; }
        public string Priority { get; set; }
        public string FinanceRequired { get; set; }
        public string CashInHand { get; set; }
        public string LoanTerm { get; set; }
        public int RateTypeID { get; set; }
        public string Frequency { get; set; }
        public Nullable<bool> IsApplicationApproved { get; set; }
        public Nullable<System.DateTime> ApprovalExpiryDate { get; set; }
        public string ReasonForNotApproval { get; set; }
        public Nullable<bool> IsAnyGuarantor { get; set; }
        public string CostOfProperty { get; set; }
        public int PropertyTypeID { get; set; }
        public Nullable<bool> IsShifted { get; set; }
        public string AgeOfProperty { get; set; }
        public string ShiftedDuration { get; set; }
        public string PropertyUsedFor { get; set; }
        public Nullable<bool> IsPropertyDecided { get; set; }
        public System.Guid AdvisorID { get; set; }
        public Nullable<System.DateTime> FinanceDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual tblAdvisorDetail tblAdvisorDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicant> tblApplicants { get; set; }
        public virtual tblMasterLoanRateType tblMasterLoanRateType { get; set; }
        public virtual tblMasterPropertyType tblMasterPropertyType { get; set; }
        public virtual tblMasterPurposeOfLoan tblMasterPurposeOfLoan { get; set; }
        public virtual tblMasterTypeOfLoan tblMasterTypeOfLoan { get; set; }
        public virtual tblMasterTypeOfStatu tblMasterTypeOfStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanGuarantor> tblLoanGuarantors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanMaster> tblLoanMasters { get; set; }
    }
}
