//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinServDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsersRole
    {
        public System.Guid UsersRoleGuid { get; set; }
        public long UsersRoleId { get; set; }
        public Nullable<System.Guid> RoleGuid { get; set; }
        public Nullable<System.Guid> UserGuid { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
